<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <RootNamespace>atividade02_pas_20261.Service</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\atividade02-pas-20262.Domain\atividade02-pas-20262.Domain.csproj" />
    </ItemGroup>
</Project>
